#!/bin/sh

action=$1
shift

case "$action" in
	conntrack)
		if [[ -e /tmp/nf_conntrack_link ]]; then
			/bin/grep -vF TIME_WAIT /tmp/nf_conntrack_link
		elif [[ -f /proc/net/nf_conntrack ]]; then
			/bin/grep -vF TIME_WAIT /proc/net/nf_conntrack
		elif [[ -x /usr/sbin/conntrack ]]; then
			/usr/sbin/conntrack -L -o extended | /bin/grep -vF TIME_WAIT
		fi
	;;
esac
