#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.XWRT >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.XWRT=/luci-static/x-wrt
		set luci.main.mediaurlbase=/luci-static/x-wrt
		commit luci
	EOF
fi

exit 0
